name: Docker
on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
jobs:
  test-docker-images:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Alpine image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packaging/docker/alpine/Dockerfile
          push: false
          tags: ${{ github.repository_owner }}/miniflux:alpine-dev
      - name: Test Alpine Docker image
        run: docker run --rm ${{ github.repository_owner }}/miniflux:alpine-dev miniflux -i
      - name: Build Distroless image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packaging/docker/distroless/Dockerfile
          push: false
          tags: ${{ github.repository_owner }}/miniflux:distroless-dev
      - name: Test Distroless Docker image
        run: docker run --rm ${{ github.repository_owner }}/miniflux:distroless-dev miniflux -i

  publish-docker-images:
    if: ${{ ! github.event.pull_request }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Distroless Docker tag
        id: docker_distroless_tag
        run: |
          DOCKER_IMAGE=${{ github.repository_owner }}/miniflux
          DOCKER_VERSION=dev-distroless
          DOCKER_VERSION=${GITHUB_REF#refs/tags/}-distroless
          TAGS="ghcr.io/${DOCKER_IMAGE}:${DOCKER_VERSION},ghcr.io/${DOCKER_IMAGE}:latest-distroless"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Distroless images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packaging/docker/distroless/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_distroless_tag.outputs.tags }}
