name: Docker
on:
  push:
    tags:
      - '*.*.*'
jobs:
  docker-images:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Alpine Docker tag
        id: docker_alpine_tag
        run: |
          DOCKER_IMAGE=${{ github.repository_owner }}/miniflux
          DOCKER_VERSION=dev
          DOCKER_VERSION=${GITHUB_REF#refs/tags/}
          TAGS="ghcr.io/${DOCKER_IMAGE}:${DOCKER_VERSION},ghcr.io/${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push Alpine images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packaging/docker/alpine/Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_alpine_tag.outputs.tags }}
