name: Docker
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish-docker-images:
    name: Publish Images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Distroless Docker tag
        id: docker_distroless_tag
        run: |
          DOCKER_IMAGE=${{ github.repository_owner }}/miniflux
          DOCKER_VERSION=${GITHUB_REF#refs/tags/}-distroless
          TAGS="ghcr.io/${DOCKER_IMAGE}:${DOCKER_VERSION},ghcr.io/${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Distroless images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/distroless/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_distroless_tag.outputs.tags }}
